[network]
name = "testnet"
node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

# Your testnet account
[[network.accounts]]
name = "deployer"
address = "ST34EECPKYV8K5P8HBXZ2KDB895V3MCDTR4P4QMAA"
# Note: You'll need to add your private key or mnemonic for actual deployment
# For security, use environment variables or Clarinet's key management
